
development:
  stripe_secret_key: 'sk_test_51K1V7jSEa1MO8D3GIx5YsPR7OggwrBi3ANEzb3c9E9VODF39gJrWs3vj3oE0ahwttkDCvZtmBXUdtvq7nU9Smrho006opYNbPl'
  stripe_publishable_key: 'pk_test_51K1V7jSEa1MO8D3GtyX6N15dgX97fE4qR0eqTByysgn7P0ztYNPtk0uBhHTraBw27sCLV6erIEUSZbPPRSqP8XO3004ujUp0DG'